POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://fonts.google.com/specimen/Rubik?query=rub&sidebar.open=true&selection.family=Montserrat:wght@300;400;500;600|Rubik:wght@600;700;800#standard-styles"
}